INSERT INTO USER_ENTITY_TABLE(USER_ID,EMAIL, FULL_NAME, MOBILE_NUMBER, PASSWORD)
VALUES(1,'abc@gmail.com','abc employee', '7282718891', 'abc');

INSERT INTO USER_ENTITY_TABLE(USER_ID,EMAIL, FULL_NAME, MOBILE_NUMBER, PASSWORD)
VALUES(2,'xyz@gmail.com','xyz employee', '7282728891', 'xyz');